### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by linxid** [PacktPublishing/Python-Artificial-Intelligence-Projects-for-Beginners#3]
Hello, Where can we find dataset used in project.  I can not open url in this web page. https://medium.com/@navdeepsingh_2336/identifying-the-genre-of-a-song-with-neural-networks-851db89c42f0
Thanks

**Comment by sagarsawant69** [comment]
Hello,

Here's the accurate link for the dataset which is used for this project http://marsyas.info/downloads/datasets.html#

Thank you
